name: Validate JSON

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Validate JSON
        run: npx tsx src/scripts/validate.ts
